---
- name: Clean User Account
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Delete Users
      user:
        name: "{{ item }}"
        state: absent
      loop:
        - enes
        - esref
        - ayse
